/**
 * 五行象法 —— 按格局名拆分，一文件一格局。
 */
export { isShuiHuoJiJi } from './shuiHuoJiJi'
export { isShuiHuoXiangZhan } from './shuiHuoXiangZhan'
export { isMuHuoXiangJian } from './muHuoXiangJian'
export { isMuHuoTongMing } from './muHuoTongMing'
export { isMuDuoHuoSai } from './muDuoHuoSai'
export { isTuJinYuXiu } from './tuJinYuXiu'
export { isTuZhongJinMai } from './tuZhongJinMai'
export { isHuoDuoJinRong } from './huoDuoJinRong'
export { isHuoWangJinShuai } from './huoWangJinShuai'
export { isJinHuoZhuYin } from './jinHuoZhuYin'
export { isHuoTuJiaDai } from './huoTuJiaDai'
export { isHuoYanTuZao } from './huoYanTuZao'
export { isShuiDuoMuPiao } from './shuiDuoMuPiao'
export { isShuiLengMuHan } from './shuiLengMuHan'
export { isShuiMuQingHua } from './shuiMuQingHua'
export { isJinHanShuiLeng } from './jinHanShuiLeng'
export { isJinBaiShuiQing } from './jinBaiShuiQing'
export { isMuShuHouTu } from './muShuHouTu'
export { isFuJinFaMu } from './fuJinFaMu'
export { judgeHanMu } from './寒木向阳'
export { judgeRiZhao } from './日照江河'
