export { isJianLuGe, isYangRenGe } from './禄刃格'
export { isZhengGuanGe } from './zhengGuanGe'
export { isQiShaGe } from './qiShaGe'
export { isShiShenGe } from './shiShenGe'
export { isShangGuanGe } from './shangGuanGe'
export { isZhengCaiGe } from './zhengCaiGe'
export { isPianCaiGe } from './pianCaiGe'
export { isZhengYinGe } from './zhengYinGe'
export { isPianYinGe } from './pianYinGe'
export { isKuiGangGe } from './kuiGangGe'
