export { isJianLuGe, isKuiGangGe, isPianCaiGe, isPianYinGe, isQiShaGe, isShangGuanGe, isShiShenYueLingGe, isYangRenGe, isZhengCaiGe, isZhengGuanGe, isZhengYinGe } from './zhenggeIndex'
export { isGuanShaHunZa, isGuanYinXiangSheng, isShaYinXiangSheng } from './guanshaIndex'
export { isShangGuanHeSha, isShangGuanJianGuan, isShangGuanPeiYin, isShangGuanShengCai, isShiShangHunZa, isShiShangXieXiu, isShiShenShengCai, isShiShenZhiSha, isXiaoShenDuoShi } from './shishangIndex'
export { isYangRenJiaSha, isYangRenJieCai } from './yangrenIndex'
export { isBiJieChongChong, isCaiDuoShenRuo, isCaiGuanYinQuan, isLuMaTongXiang, isYiCaiPoYin } from './zongliangIndex'
export { isFuJinFaMu, isHuoDuoJinRong, isHuoTuJiaDai, isHuoWangJinShuai, isHuoYanTuZao, isJinBaiShuiQing, isJinHanShuiLeng, isJinHuoZhuYin, isMuDuoHuoSai, isMuHuoTongMing, isMuHuoXiangJian, isMuShuHouTu, isShuiDuoMuPiao, isShuiHuoJiJi, isShuiHuoXiangZhan, isShuiLengMuHan, isShuiMuQingHua, isTuJinYuXiu, isTuZhongJinMai, judgeHanMu, judgeRiZhao } from './wuxingIndex'
export { isZhuanWangGe } from './专旺'
export { isCongGe } from './从格'
export { isDiWangMingZao, isHuaQiGe, isJieCaiJianCai, isLiangQiChengXiang, isRenQiLongBei, isRiDeGe, isRiGuiGe, isSanGengGe, isSanQiGe, isShenShaLiangTing, isTianYuanYiQi } from './teshuIndex'
